auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 黄雄镖的博客
url: BillBillBillBill.github.io
feed: /atom.xml
author_info: <a href="http:BillBillBillBill.github.io/">BillBillBillBill</a>
